debug:
    false
server:
    port:8080

# DATASOURCE
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&amp;charaterEncoding=utf-8
    databaseName: test
    serverName: 127.0.0.1
    username: root
    password: 
    cachePrepStmts: true
    prepStmtsSize: 250
    prepStmtsCacheSqlLimit: 2048
    userServerPrepStmts: true


# MyBatis
mybatis:
    typeAliasesPackage: com.mycompany.app.model
    mapperLocations: classpath:/com/mycompany/app/dao/mapper/mybatis/*.xml

# LOGGING
logging:
    level:
       com.ibatis:DEBUG
